pool:
  vmImage: macOS-10.15
trigger:
- buildbranch_osx
pr: none
stages:
- stage: stage_0
  jobs:
  - job: stage_0_job_0
    steps:
    - script: |-
        \
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-rviz-assimp-vendor ros-galactic-rviz-ogre-vendor
          ros-galactic-rviz-rendering
      displayName: Build ros-galactic-rviz-assimp-vendor ros-galactic-rviz-ogre-vendor
        ros-galactic-rviz-rendering
- stage: stage_1
  jobs:
  - job: stage_1_job_0
    steps:
    - script: |-
        \
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-rviz-rendering-tests ros-galactic-rviz-common
          ros-galactic-rviz-visual-testing-framework ros-galactic-rviz-default-plugins
      displayName: Build ros-galactic-rviz-rendering-tests ros-galactic-rviz-common
        ros-galactic-rviz-visual-testing-framework ros-galactic-rviz-default-plugins
- stage: stage_2
  jobs:
  - job: stage_2_job_0
    steps:
    - script: |-
        \
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-rviz2
      displayName: Build ros-galactic-rviz2
