package:
  name: ros-galactic-nav2-regulated-pure-pursuit-controller
  version: 1.0.6
source:
  git_url: https://github.com/SteveMacenski/navigation2-release.git
  git_rev: release/galactic/nav2_regulated_pure_pursuit_controller/1.0.6-1
  folder: ros-galactic-nav2-regulated-pure-pursuit-controller/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-geometry-msgs
    - ros-galactic-nav2-common
    - ros-galactic-nav2-core
    - ros-galactic-nav2-costmap-2d
    - ros-galactic-nav2-msgs
    - ros-galactic-nav2-util
    - ros-galactic-pluginlib
    - ros-galactic-rclcpp
    - ros-galactic-tf2
  run:
    - python
    - ros-galactic-geometry-msgs
    - ros-galactic-nav2-common
    - ros-galactic-nav2-core
    - ros-galactic-nav2-costmap-2d
    - ros-galactic-nav2-msgs
    - ros-galactic-nav2-util
    - ros-galactic-pluginlib
    - ros-galactic-rclcpp
    - ros-galactic-ros-workspace
    - ros-galactic-tf2
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
