package:
  name: ros-galactic-rviz-default-plugins
  version: 8.5.0
source:
  git_url: https://github.com/ros2-gbp/rviz-release.git
  git_rev: release/galactic/rviz_default_plugins/8.5.0-3
  folder: ros-galactic-rviz-default-plugins/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - qt 5
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-cppcheck
    - ros-galactic-ament-cmake-cpplint
    - ros-galactic-ament-cmake-gmock
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-cmake-lint-cmake
    - ros-galactic-ament-cmake-uncrustify
    - ros-galactic-ament-cmake-xmllint
    - ros-galactic-ament-index-cpp
    - ros-galactic-ament-lint-auto
    - ros-galactic-geometry-msgs
    - ros-galactic-interactive-markers
    - ros-galactic-laser-geometry
    - ros-galactic-map-msgs
    - ros-galactic-nav-msgs
    - ros-galactic-pluginlib
    - ros-galactic-rclcpp
    - ros-galactic-resource-retriever
    - ros-galactic-rviz-common
    - ros-galactic-rviz-ogre-vendor
    - ros-galactic-rviz-rendering
    - ros-galactic-rviz-rendering-tests
    - ros-galactic-rviz-visual-testing-framework
    - ros-galactic-tf2
    - ros-galactic-tf2-geometry-msgs
    - ros-galactic-tf2-ros
    - ros-galactic-urdf
    - ros-galactic-visualization-msgs
  run:
    - python
    - qt
    - ros-galactic-geometry-msgs
    - ros-galactic-interactive-markers
    - ros-galactic-laser-geometry
    - ros-galactic-map-msgs
    - ros-galactic-nav-msgs
    - ros-galactic-pluginlib
    - ros-galactic-rclcpp
    - ros-galactic-resource-retriever
    - ros-galactic-ros-workspace
    - ros-galactic-rviz-common
    - ros-galactic-rviz-ogre-vendor
    - ros-galactic-rviz-rendering
    - ros-galactic-tf2
    - ros-galactic-tf2-geometry-msgs
    - ros-galactic-tf2-ros
    - ros-galactic-urdf
    - ros-galactic-visualization-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
